### ISSUE TITLE
Make coverage work

### ISSUE THREAD

**Issue by oberstet** [xbr/xbr-protocol#8]
tryin to get coverage running, I wasted like 3h getting over the "gas limit exceeded" problem (the instrumented smart contracts require more gas to deploy, sure, but the gas settings are already high):

```
(cpy371_1) oberstet@thinkpad-x1:~/scm/xbr/xbr-protocol$ make coverage 
#./node_modules/.bin/solidity-coverage
npm run coverage

> xbr@18.11.3 coverage /home/oberstet/scm/xbr/xbr-protocol
> solidity-coverage

Generating coverage environment
Running: truffle compile --network coverage 
(this can take a few seconds)...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/XBRMaintained.sol...
Compiling ./contracts/XBRNetwork.sol...
Compiling ./contracts/XBRNetworkProxy.sol...
Compiling ./contracts/XBRPaymentChannel.sol...
Compiling ./contracts/XBRToken.sol...
Compiling openzeppelin-solidity/contracts/access/Roles.sol...
Compiling openzeppelin-solidity/contracts/cryptography/ECDSA.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/IERC20.sol...
Writing artifacts to ./build/contracts

Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Skipping instrumentation of  ./coverageEnv/contracts/XBRMaintained.sol
Skipping instrumentation of  ./coverageEnv/contracts/XBRNetwork.sol
Skipping instrumentation of  ./coverageEnv/contracts/XBRNetworkProxy.sol
Skipping instrumentation of  ./coverageEnv/contracts/XBRPaymentChannel.sol
Instrumenting  ./coverageEnv/contracts/XBRToken.sol
Running: truffle compile --network coverage 
(this can take a few seconds)...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/XBRMaintained.sol...
Compiling ./contracts/XBRNetwork.sol...
Compiling ./contracts/XBRNetworkProxy.sol...
Compiling ./contracts/XBRPaymentChannel.sol...
Compiling ./contracts/XBRToken.sol...
Compiling openzeppelin-solidity/contracts/access/Roles.sol...
Compiling openzeppelin-solidity/contracts/cryptography/ECDSA.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/IERC20.sol...

Compilation warnings encountered:
...

Writing artifacts to ./build/contracts

Launched testrpc on port 8555
Running: truffle test --network coverage 
(this can take a few seconds)...
Using network 'coverage'.

Error: Exceeds block gas limit
    at Object.InvalidResponse (/home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/oberstet/scm/xbr/xbr-protocol/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Cleaning up...
Shutting down testrpc-sc (pid 8921)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "coverage"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! xbr@18.11.3 coverage: `solidity-coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xbr@18.11.3 coverage script 'solidity-coverage'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xbr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     solidity-coverage
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xbr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xbr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oberstet/scm/xbr/xbr-protocol/npm-debug.log
Makefile:55: recipe for target 'coverage' failed
make: *** [coverage] Error 1
(cpy371_1) oberstet@thinkpad-x1:~/scm/xbr/xbr-protocol$ 
```

**Comment by oberstet** [comment]
Works now:

* https://travis-ci.org/xbr/xbr-protocol/jobs/463437882#L1332
* https://codecov.io/github/xbr/xbr-protocol
